name = "fauna-workers"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-02-13"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
